import 'package:flutter/material.dart';
import 'package:flutter_netflix_ui/assets.dart';

import 'models/content.dart';

const Content sintelContent = Content(
  name: 'Sintel',
  imageUrl: Assets.sintel,
  titleImageUrl: Assets.sintelTitle,
  videoUrl: Assets.sintelVideoUrl,
  description:
      'A lonely young woman, Sintel, helps and befriends a dragon,\nwhom she calls Scales. But when he is kidnapped by an adult\ndragon, Sintel decides to embark on a dangerous quest to find\nher lost friend Scales.',
  color: null,
);

const List<Content> previews = [
  Content(
    name: 'Avatar The Last Airbender',
    imageUrl: Assets.atla,
    color: Colors.orange,
    titleImageUrl: Assets.atlaTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    color: Colors.red,
    titleImageUrl: Assets.crownTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    color: Colors.yellow,
    titleImageUrl: Assets.umbrellaAcademyTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'Carole and Tuesday',
    imageUrl: Assets.caroleAndTuesday,
    color: Colors.lightBlueAccent,
    titleImageUrl: Assets.caroleAndTuesdayTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    color: Colors.green,
    titleImageUrl: Assets.blackMirrorTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'Avatar The Last Airbender',
    imageUrl: Assets.atla,
    color: Colors.orange,
    titleImageUrl: Assets.atlaTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    color: Colors.red,
    titleImageUrl: Assets.crownTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    color: Colors.yellow,
    titleImageUrl: Assets.umbrellaAcademyTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'Carole and Tuesday',
    imageUrl: Assets.caroleAndTuesday,
    color: Colors.lightBlueAccent,
    titleImageUrl: Assets.caroleAndTuesdayTitle,
    description: '',
    videoUrl: '',
  ),
  Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    color: Colors.green,
    titleImageUrl: Assets.blackMirrorTitle,
    description: '',
    videoUrl: '',
  ),
];

const List<Content> myList = [
  Content(
    name: 'Violet Evergarden',
    imageUrl: Assets.violetEvergarden,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'How to Sell Drugs Online (Fast)',
    imageUrl: Assets.htsdof,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Kakegurui',
    imageUrl: Assets.kakegurui,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Carole and Tuesday',
    imageUrl: Assets.caroleAndTuesday,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Violet Evergarden',
    imageUrl: Assets.violetEvergarden,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'How to Sell Drugs Online (Fast)',
    imageUrl: Assets.htsdof,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Kakegurui',
    imageUrl: Assets.kakegurui,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Carole and Tuesday',
    imageUrl: Assets.caroleAndTuesday,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Black Mirror',
    imageUrl: Assets.blackMirror,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
];

const List<Content> originals = [
  Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Stranger Things',
    imageUrl: Assets.strangerThings,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Witcher',
    imageUrl: Assets.witcher,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Umbrella Academy',
    imageUrl: Assets.umbrellaAcademy,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: '13 Reasons Why',
    imageUrl: Assets.thirteenReasonsWhy,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The End of the F***ing World',
    imageUrl: Assets.teotfw,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
];

const List<Content> trending = [
  Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Avatar The Last Airbender',
    imageUrl: Assets.atla,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Tiger King',
    imageUrl: Assets.tigerKing,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Dogs',
    imageUrl: Assets.dogs,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Explained',
    imageUrl: Assets.explained,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Avatar The Last Airbender',
    imageUrl: Assets.atla,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Tiger King',
    imageUrl: Assets.tigerKing,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'The Crown',
    imageUrl: Assets.crown,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
  Content(
    name: 'Dogs',
    imageUrl: Assets.dogs,
    color: null,
    description: '',
    titleImageUrl: '',
    videoUrl: '',
  ),
];
